### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by cjkzwe** [nopnop2002/esp-idf-ili9340#40]
I wanna know that what is the difference between the "DC GPIO" and "BACKLIGHT GPIO"?

**Comment by nawazawanswl** [comment]
"DC GPIO" = Data or Command signal to SPI slave( a gegeral pupose IO pin to notify if the  input data to slave is a command or Data )
"BACKLIGHT GPIO" = a gegeral pupose IO pin to turn on or off  BACKLIGHT of Display.
if backlight is off TFT will not show anything ( either if its running properly )

**Comment by cjkzwe** [comment]
OK ,Copy that (Although I have solved by reading code myself). Thank you, and I'll do some test when my screen reaches.

**Comment by nawazawanswl** [comment]
ok, good luck
