### ISSUE TITLE
Slow loading speed

### ISSUE THREAD

**Issue by nikhil-robinson** [nopnop2002/esp-idf-ili9340#41]
I was testing this on the st7735 lcd display 128x128 but the loading speed is too slow , i have used the esp32s3 module for this drawing fill circle is comming as line by line.

**Comment by nopnop2002** [comment]
Not yet supporting ESP32S3.

**Comment by nikhil-robinson** [comment]
@nopnop2002   i have manged to run the program and am able to show image and draw pixels but the loading speed in so slow , pixel by pixel

**Comment by nopnop2002** [comment]
The SPI of ESP32S3 is different from the others.

**Comment by nikhil-robinson** [comment]
so is there any way to make it work ? can you suggest a fix?

**Comment by nopnop2002** [comment]
I haven't got the ESP32S3 yet.
II will support it when i get ESP32S3.

**Comment by nopnop2002** [comment]
I found that there are limits to the GPIOs that can be used as touch panel controls.

As a result of many experiments, I found a pin assignment that works on the touch panel.

**Comment by nikhil-robinson** [comment]
Hi @nopnop2002 , Thanks for the followup can you specify which GPIO pins should be used ?  Thanks.

**Comment by nopnop2002** [comment]
Try this:
T_CS and T_IRQ need to be changed between S2 and S3

## Wirering for XPT2046  

|TFT||ESP32|ESP32-S2|ESP32-S3|ESP32-C3||
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|VCC|--|3.3V|3.3V|3.3V|3V3||
|GND|--|GND|GND|GND|GND||
|CS|--|GPIO14|GPIO34|GPIO34|GPIO9||
|RES|--|GPIO33|GPIO41|GPIO41|GPIO1|(*1)|
|D/C|--|GPIO27|GPIO40|GPIO40|GPIO10|(*1)|
|MOSI|--|GPIO23|GPIO35|GPIO35|GPIO19|(*2)|
|SCK|--|GPIO18|GPIO36|GPIO36|GPIO18|(*2)|
|LED|--|3.3V|3.3V|3.3V|3.3V|(*3)|
|MISO|--|N/C|N/C|N/C|N/C||
|T_CLK|--|GPIO18|GPIO36|GPIO36|GPIO18|(*2)|
|T_CS|--|GPIO22|GPIO38|GPIO42|GPIO5|(*4)|
|T_DIN|--|GPIO23|GPIO35|GPIO35|GPIO19|(*2)|
|T_OUT|--|GPIO19|GPIO37|GPIO37|GPIO3|(*2)|
|T_IRQ|--|GPIO21|GPIO39|GPIO45|GPIO4|(*4)|


(*1) You can change any pin.   

(*2) SPI is shared by TFT and XPT2046.   

(*3) It can be controlled using gpio. However, you need to switch 3.3V using a transistor.   

(*4) I found that there are limits to the GPIOs that can be used as touch panel controls.
