### ISSUE TITLE
How to display jpeg or rgb565 from memory buffer ?

### ISSUE THREAD

**Issue by earthPerson-001** [nopnop2002/esp-idf-ili9340#45]
I want to display images from camera frame buffer captured by esp32-cam. Following is the code snippet.

```c
TickType_t realtime_image_test(TFT_t * dev, camera_fb_t * fb, int width, int height) {

	TickType_t startTick, endTick, diffTick;
	startTick = xTaskGetTickCount();

	// lcdFillScreen(dev, BLACK);  // not filling can make it look better

	int _width = width;
	if (width > 240) _width = 240;
	int _height = height;
	if (height > 320) _height = 320;

	int image_width = fb->width;
	int image_height = fb->height;

	uint16_t jpegWidth = width;
	uint16_t offsetX = 0;
	if (width > image_width) {
		jpegWidth = image_width;
		offsetX = (width - image_width) / 2;
	}
	ESP_LOGD(__FUNCTION__, "jpegWidth=%d offsetX=%d", jpegWidth, offsetX);

	uint16_t jpegHeight = height;
	uint16_t offsetY = 0;
	if (height > image_height) {
		jpegHeight = image_height;
		offsetY = (height - image_height) / 2;
	}
	ESP_LOGD(__FUNCTION__, "jpegHeight=%d offsetY=%d", jpegHeight, offsetY);

	// when the buffer itself is in rgb888 format
	// uint8_t *pixels = fb->buf;  

	// when the buffer is in jpeg format
	uint8_t *pixels = malloc(fb->width * fb->height * 3);
	if (!fmt2rgb888(fb->buf, fb->len, fb->format, pixels)) {
		ESP_LOGE(TAG, "Conversion from jpeg to rgb888 failed");
	}

	uint16_t *colors = (uint16_t*)malloc(sizeof(uint16_t) * jpegWidth);
	uint8_t r,g,b;
	for(int y = 0; y < jpegHeight; y++){
		for(int x = 0;x < jpegWidth; x++){
			r = pixels[y*jpegWidth + x*3];
			g = pixels[y*jpegWidth + x*3 + 1];
			b = pixels[y*jpegWidth + x*3 + 2];
			colors[x] = rgb565(r,g,b); // convert rgb888 to rgb565
		}
		lcdDrawMultiPixels(dev, offsetX, y+offsetY, jpegWidth, colors);
		vTaskDelay(1);
	}
	free(colors);
	free(pixels); // no need to free when the original buffer of camera is used

	endTick = xTaskGetTickCount();
	diffTick = endTick - startTick;
	ESP_LOGI(__FUNCTION__, "elapsed time[ms]:%"PRIu32,diffTick*portTICK_PERIOD_MS);
	return diffTick;
}
```

What this code does is convert the image present as jpeg in buffer to rgb888 format and reformats it as rgb565 which is presume is the one used by tft display. The exact display is st7735.

The problem is that, the image displayed isn't correct. What am I doing wrong ?
![image](https://github.com/nopnop2002/esp-idf-ili9340/assets/85444310/a8c240da-01b4-4b47-a587-c0ba6e799965)

**Comment by nopnop2002** [comment]
The X and Y alignment of images may not match between fmt2rgb888 and lcdDrawMultiPixels.

You need to check which one is correct.

pixels[1][2]-->screeen[1][2]
pixels[1][2]-->screeen[2][1]
pixels[1][2]-->screeen[width-1][1]
pixels[1][2]-->screeen[height-1][1]
pixels[1][2]-->screeen[1][width-1]
pixels[1][2]-->screeen[1][height-1]

**Comment by earthPerson-001** [comment]
> The X and Y alignment of images may not match between fmt2rgb888 and lcdDrawMultiPixels.

Aren't all of them calling the same jpeg decoder function? Can you clarify what it exactly means? Are there empty spaces in the buffer or something else?

Since the frame buffer type is uint8_t* and the image returned from fmt2rgb888 is of the same type, I assumed, that one-pixel data is separated into three adjacent buffer indices.

I also tried to use the rgb565 frame buffer directly, but the issue is similar (the image produced is of a different colour). In this case, there wasn't enough documentation from espressif/esp-cam as to how the rgb565 value was stored in the uint8_t buffer.

**Comment by nopnop2002** [comment]
>Aren't all of them calling the same jpeg decoder function?

You need to check if they are the same.

> also tried to use the rgb565 frame buffe

Since rgb565 is a very general format, it's easy to see how rgb565 values ​​are stored in uint8_t buffers.

#define rgb565(r, g, b) (((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))

>Since the frame buffer type is uint8_t* and the image returned from fmt2rgb888 is of the same type, I assumed, that one-pixel data is separated into three adjacent buffer indices.

You need to prove that assumption.

Code based on assumptions is almost always incorrect.

**Comment by nopnop2002** [comment]
The biggest problem is that the number of pixels on the FB and the number of pixels on the TFT do not match.

Converting a 1024x768 FB with fmt2rgb888 will result in a 1024x768 RGB image.

To display it on a TFT, you need a TFT with the same number of pixels.

```
	// when the buffer is in jpeg format
	uint8_t *pixels = malloc(fb->width * fb->height * 3);
	if (!fmt2rgb888(fb->buf, fb->len, fb->format, pixels)) {
		ESP_LOGE(TAG, "Conversion from jpeg to rgb888 failed");
	}
```

The pixel array is an image the size of the FB. (fb->width * fb->height)

```
	uint16_t *colors = (uint16_t*)malloc(sizeof(uint16_t) * jpegWidth);
	uint8_t r,g,b;
	for(int y = 0; y < jpegHeight; y++){
		for(int x = 0;x < jpegWidth; x++){
			r = pixels[y*jpegWidth + x*3];
			g = pixels[y*jpegWidth + x*3 + 1];
			b = pixels[y*jpegWidth + x*3 + 2];
			colors[x] = rgb565(r,g,b); // convert rgb888 to rgb565
		}
		lcdDrawMultiPixels(dev, offsetX, y+offsetY, jpegWidth, colors);
		vTaskDelay(1);
	}
```

The above code does not perform any reduction.

It is possible to display only part of the FB by calculating the position of the pixels array correctly.

```
pos = any caluculation
r = pixels[pos];
g = pixels[pos+1];
b = pixels[pos+2];
```

```
FB IMAGE                      TFT AREA
+--------------------------+ +----------+
|xxxxxxxxxx                | |xxxxxxxxxx|
|xxxxxxxxxx                | |xxxxxxxxxx|
|xxxxxxxxxx                | |xxxxxxxxxx|
|xxxxxxxxxx                | |xxxxxxxxxx|
|xxxxxxxxxx                | |xxxxxxxxxx|
|xxxxxxxxxx                | |xxxxxxxxxx|
|                          | +----------+
|                          |
|                          |
|                          |
|                          |
|                          |
|                          |
|                          |
|                          |
+--------------------------+
```
