### ISSUE TITLE
How to add new images/icons?

### ISSUE THREAD

**Issue by majorBien** [nopnop2002/esp-idf-ili9340#47]
Hello,
I'd like to ask for a tip how to add any new image or icon. I added a .png file into a folder "images" but when I chose this file using the ShowPngImage function nothing shows. I suppose that there is neccesary any additional operation. Could you give me an advice?
Best Regards.
majorBien

**Comment by nopnop2002** [comment]
Place the new image in the images folder and build it to enable it.
There are no additional actions required.
Adding a large size image will result in a build error.


You can check the valid images and partition sizes here.
https://github.com/nopnop2002/esp-idf-ili9340/blob/master/main/main.c#L2388

There's not much space.

```
I (590) MAIN: Mount /images to storage2 success
I (590) MAIN: Partition size: total: 655361, used: 597380
I (590) listSPIFFS: d_name=linkedin.png d_ino=0 d_type=1
I (600) listSPIFFS: d_name=git.png d_ino=0 d_type=1
I (610) listSPIFFS: d_name=instagram.png d_ino=0 d_type=1
I (610) listSPIFFS: d_name=esp32_ro.bmp d_ino=0 d_type=1
I (630) listSPIFFS: d_name=youtube.png d_ino=0 d_type=1
I (630) listSPIFFS: d_name=esp_logo.png d_ino=0 d_type=1
I (630) listSPIFFS: d_name=esp32.jpeg d_ino=0 d_type=1
I (640) listSPIFFS: d_name=esp32.bmp d_ino=0 d_type=1
I (650) listSPIFFS: d_name=vkontakte.png d_ino=0 d_type=1
I (650) listSPIFFS: d_name=whatsapp.png d_ino=0 d_type=1
I (650) listSPIFFS: d_name=facebook.png d_ino=0 d_type=1
I (660) listSPIFFS: d_name=twitter.png d_ino=0 d_type=1
```

**Comment by majorBien** [comment]
Okay, I changed the image file on another and now it works perfect. Something was wrong with my previus image. Thank you for the fast answer :D
