### ISSUE TITLE
Undefined reference when including ili9340 as component

### ISSUE THREAD

**Issue by MihaelGolob** [nopnop2002/esp-idf-ili9340#48]
Hello, I'm having some problems adding this library as a component to my project. What I did is simply copy the components/ili9340 directory and put it into my components directory. The project builds fine, but when I try to use one of the function e.g. spi_master_init, I get `undefined reference to` linking errors.  If I just download the whole esp-idf-ili9340 repository I can build and flash it successfully.

**Comment by nopnop2002** [comment]
```
cp -r esp-idf-ili9340/components your_project
cp -r esp-idf-ili9340/font your_project
cp sdkconfig.defaults your_project
cd your_project
edit partitions.csv
rm -r build
rm sdkconfig
idf.py menuconfig
idf.py build
```

**Comment by nopnop2002** [comment]
I'm going to close this issue. You can reopen it at any time.
